import { onDocumentUpdated } from 'firebase-functions/v2/firestore';
import * as admin from 'firebase-admin';

/**
 * Canonical payout status lifecycle.
 */
export type PayoutStatus = 'pending' | 'processing' | 'paid';

/**
 * Document shape stored in the 'agent_payouts' Firestore collection.
 * One document is created per successfully delivered order.
 */
export interface AgentPayout {
  /** Unique ID of the payout document (auto-generated by Firestore) */
  id: string;
  /** UID of the delivery agent who completed the delivery */
  agentId: string;
  /** The delivery order ID this payout is tied to */
  deliveryId: string;
  /** Fixed payout amount in INR for a completed delivery */
  amount: number;
  /** Timestamp when the payout record was created (i.e. when delivery was completed) */
  date: admin.firestore.Timestamp;
  /** Processing state of the payout — starts as 'pending' until disbursed */
  status: PayoutStatus;
}

/**
 * Firestore trigger: fires whenever a document in the 'deliveries' collection is updated.
 *
 * Conditions that activate the payout logic:
 *   - The delivery status BEFORE the update was NOT 'delivered'
 *   - The delivery status AFTER the update IS 'delivered'
 *
 * Actions performed (inside a Firestore batch for atomicity):
 *   1. Creates a new document in 'agent_payouts' with ₹40 payout for the agent.
 *   2. Increments the agent's 'daily_earnings' field on their user document by 40.
 */
export const onDeliveryCompletedPayout = onDocumentUpdated(
  'deliveries/{orderId}',
  async (event) => {
    const change = event.data;
    if (!change) {
      console.log('[onDeliveryCompletedPayout] No data change payload — skipping.');
      return;
    }

    const beforeData = change.before.data();
    const afterData = change.after.data();

    if (!beforeData || !afterData) {
      console.log('[onDeliveryCompletedPayout] Missing before/after data — skipping.');
      return;
    }

    const beforeStatus = beforeData.status as string;
    const afterStatus = afterData.status as string;

    // Only proceed on the exact transition to 'delivered'
    if (beforeStatus === 'delivered' || afterStatus !== 'delivered') {
      console.log(
        `[onDeliveryCompletedPayout] Skipping — transition ${beforeStatus} → ${afterStatus} is not a delivery completion.`
      );
      return;
    }

    const orderId = event.params.orderId;
    const agentId = afterData.agentId as string | undefined;

    if (!agentId) {
      console.error(
        `[onDeliveryCompletedPayout] Delivery ${orderId} has no agentId. Cannot create payout.`
      );
      return;
    }

    const db = admin.firestore();
    const PAYOUT_AMOUNT = 40; // ₹40 fixed per delivery

    console.log(
      `[onDeliveryCompletedPayout] Delivery ${orderId} completed by agent ${agentId}. Creating payout of ₹${PAYOUT_AMOUNT}.`
    );

    try {
      // --- Idempotency check ---
      const existingPayout = await db.collection('agent_payouts')
        .where('deliveryId', '==', orderId)
        .limit(1)
        .get();

      if (!existingPayout.empty) {
        console.log(`[onDeliveryCompletedPayout] Payout already exists for delivery ${orderId}. Skipping.`);
        return;
      }

      // --- Prepare references ---
      const payoutRef = db.collection('agent_payouts').doc(); // auto-ID
      const agentUserRef = db.collection('users').doc(agentId);

      // --- Build the payout record ---
      const payoutRecord: Omit<AgentPayout, 'id'> = {
        agentId,
        deliveryId: orderId,
        amount: PAYOUT_AMOUNT,
        date: admin.firestore.Timestamp.now(),
        status: 'pending',
      };

      // --- Atomic batch write ---
      // Using a WriteBatch so both the payout creation and the earnings increment
      // either both succeed or both fail — no partial state.
      const batch = db.batch();

      // 1. Write the canonical payout record
      batch.set(payoutRef, payoutRecord);

      // 2. Atomically increment daily_earnings on the agent's user document.
      batch.update(agentUserRef, {
        daily_earnings: admin.firestore.FieldValue.increment(PAYOUT_AMOUNT),
      });

      await batch.commit();

      console.log(
        `[onDeliveryCompletedPayout] Payout ${payoutRef.id} created and daily_earnings incremented for agent ${agentId}.`
      );
    } catch (err) {
      console.error(
        `[onDeliveryCompletedPayout] Failed to create payout for delivery ${orderId}:`,
        err
      );
    }
  }
);

/**
 * Firestore trigger: fires whenever a document in the canonical 'orders' collection is updated.
 * Automatically provisions rider earnings and agent_payout record when order status transitions to 'delivered'.
 */
export const onOrderCompletedPayout = onDocumentUpdated(
  'orders/{orderId}',
  async (event) => {
    const change = event.data;
    if (!change) return;

    const beforeData = change.before.data();
    const afterData = change.after.data();

    if (!beforeData || !afterData) return;

    const beforeStatus = beforeData.status as string;
    const afterStatus = afterData.status as string;

    // Only proceed on the exact transition to 'delivered'
    if (beforeStatus === 'delivered' || afterStatus !== 'delivered') {
      return;
    }

    const orderId = event.params.orderId;
    const agentId = (afterData.rider_id || afterData.driverId || afterData.agentId || afterData.agent_id) as string | undefined;

    if (!agentId) {
      console.log(`[onOrderCompletedPayout] Order ${orderId} has no assigned rider/agent ID. Skipping payout.`);
      return;
    }

    const db = admin.firestore();
    const PAYOUT_AMOUNT = 40; // ₹40 fixed per delivered order

    try {
      // Idempotency check: ensure payout has not already been created for this order
      const existingPayout = await db.collection('agent_payouts')
        .where('deliveryId', '==', orderId)
        .limit(1)
        .get();

      if (!existingPayout.empty) {
        console.log(`[onOrderCompletedPayout] Payout already recorded for order ${orderId}. Skipping.`);
        return;
      }

      const payoutRef = db.collection('agent_payouts').doc();
      const agentUserRef = db.collection('users').doc(agentId);

      const payoutRecord: Omit<AgentPayout, 'id'> = {
        agentId,
        deliveryId: orderId,
        amount: PAYOUT_AMOUNT,
        date: admin.firestore.Timestamp.now(),
        status: 'pending',
      };

      const batch = db.batch();
      batch.set(payoutRef, payoutRecord);
      batch.update(agentUserRef, {
        daily_earnings: admin.firestore.FieldValue.increment(PAYOUT_AMOUNT),
      });

      await batch.commit();

      console.log(
        `[onOrderCompletedPayout] Payout ${payoutRef.id} created and daily_earnings incremented for rider ${agentId} on order ${orderId}.`
      );
    } catch (err) {
      console.error(`[onOrderCompletedPayout] Failed to create payout for order ${orderId}:`, err);
    }
  }
);
