"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateTestDelivery = exports.onSubscriptionCancelled = exports.onSubscriptionCreated = exports.markBatchReady = exports.autoGenerateDailyDeliveries = exports.generateTodayDeliveries = exports.updateDeliveryStatus = exports.onOrderStatusChange = void 0;
const firestore_1 = require("firebase-functions/v2/firestore");
const https_1 = require("firebase-functions/v2/https");
const scheduler_1 = require("firebase-functions/v2/scheduler");
const admin = __importStar(require("firebase-admin"));
const events_1 = require("./utils/events");
exports.onOrderStatusChange = (0, firestore_1.onDocumentUpdated)('orders/{orderId}', async (event) => {
    const before = event.data?.before.data();
    const after = event.data?.after.data();
    if (!before || !after)
        return;
    if (before.status === after.status)
        return;
    const afterStatus = after.status;
    const customerId = after.user_id;
    const orderId = event.params.orderId;
    console.log(`[onOrderStatusChange] Order ${orderId} transitioned: ${before.status} -> ${afterStatus}`);
    try {
        if (afterStatus === 'vendor_notified') {
            await (0, events_1.publishEvent)('order_confirmed', customerId, 'customer', `confirmed_${orderId}`, {
                mealType: after.meal_type || 'meal',
                slot: after.delivery_slot || 'your requested time'
            });
        }
        else if (afterStatus === 'vendor_preparing' || afterStatus === 'vendor_ready') {
            if (afterStatus === 'vendor_preparing') {
                await (0, events_1.publishEvent)('meal_prep_started', customerId, 'customer', `prep_${orderId}`, {
                    mealType: after.meal_type || 'meal'
                });
            }
        }
        else if (afterStatus === 'picked_up') {
            await (0, events_1.publishEvent)('meal_picked_up', customerId, 'customer', `pickup_${orderId}`, {});
        }
        else if (afterStatus === 'out_for_delivery') {
            await (0, events_1.publishEvent)('rider_en_route', customerId, 'customer', `enroute_${orderId}`, {});
        }
        else if (afterStatus === 'delivered') {
            await (0, events_1.publishEvent)('meal_delivered', customerId, 'customer', `deliv_${orderId}`, {});
        }
        else if (afterStatus === 'failed') {
            await (0, events_1.publishEvent)('delivery_failed', customerId, 'customer', `fail_${orderId}`, {
                reason: after.failureReason || 'Unknown error'
            });
        }
    }
    catch (err) {
        console.error(`[onOrderStatusChange] Failed processing push trigger for ${orderId}:`, err);
    }
});
exports.updateDeliveryStatus = (0, https_1.onCall)(async (request) => {
    const { data, auth } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    if (auth.token.role !== 'delivery_agent' && auth.token.role !== 'delivery') {
        throw new https_1.HttpsError('permission-denied', 'Must be a delivery agent to update status');
    }
    const { orderId, status, reason } = data;
    if (!orderId || !status) {
        throw new https_1.HttpsError('invalid-argument', 'Missing orderId or status');
    }
    const db = admin.firestore();
    const deliveryRef = db.collection('deliveries').doc(orderId);
    const transitionResult = await db.runTransaction(async (transaction) => {
        const docSnap = await transaction.get(deliveryRef);
        if (!docSnap.exists) {
            throw new https_1.HttpsError('not-found', 'Delivery order not found');
        }
        const deliveryData = docSnap.data();
        if (deliveryData.agentId !== auth.uid) {
            throw new https_1.HttpsError('permission-denied', 'You are not assigned to this delivery');
        }
        const currentStatus = deliveryData.status;
        if (status === 'picked_up' && currentStatus !== 'pending') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to picked_up from pending');
        }
        if (status === 'delivered' && currentStatus !== 'picked_up') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to delivered from picked_up');
        }
        if (status === 'failed_attempt' && currentStatus !== 'picked_up') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to failed_attempt from picked_up');
        }
        if (status === 'failed_attempt' && (!reason || reason.trim() === '')) {
            throw new https_1.HttpsError('invalid-argument', 'Must provide a non-empty reason when setting status to failed_attempt');
        }
        const updatePayload = {
            status,
            statusHistory: admin.firestore.FieldValue.arrayUnion({
                status,
                timestamp: admin.firestore.FieldValue.serverTimestamp(),
                agentId: auth.uid
            })
        };
        if (status === 'delivered') {
            updatePayload.delivered_at = admin.firestore.FieldValue.serverTimestamp();
        }
        else if (status === 'failed_attempt') {
            updatePayload.failedReason = reason;
        }
        transaction.update(deliveryRef, updatePayload);
        return {
            customerId: deliveryData.customerId,
            vendorId: deliveryData.vendorId,
            oldStatus: currentStatus,
            newStatus: status,
            reason: reason
        };
    });
    try {
        const { customerId, newStatus, reason } = transitionResult;
        if (newStatus === 'picked_up') {
            await (0, events_1.publishEvent)('meal_picked_up', customerId, 'customer', `meal_picked_up_${orderId}`, { orderId });
        }
        else if (newStatus === 'delivered') {
            await (0, events_1.publishEvent)('meal_delivered', customerId, 'customer', `meal_delivered_${orderId}`, { orderId });
        }
        else if (newStatus === 'failed_attempt') {
            await (0, events_1.publishEvent)('delivery_failed', customerId, 'customer', `delivery_failed_${orderId}`, { orderId, reason: reason ?? '' });
            const adminSnap = await db.collection('users').where('role', '==', 'admin').get();
            await Promise.all(adminSnap.docs.map((adminDoc) => (0, events_1.publishEvent)('delivery_failed', adminDoc.id, 'admin', `delivery_failed_admin_${orderId}_${adminDoc.id}`, { orderId, reason: reason ?? '' })));
        }
    }
    catch (error) {
        console.error(`[updateDeliveryStatus] Push notification error for order ${orderId}:`, error);
    }
    return {
        success: true,
        newStatus: transitionResult.newStatus,
        message: `Successfully updated order status to ${transitionResult.newStatus}`
    };
});
async function processDailyDeliveries(force = false) {
    const db = admin.firestore();
    const result = { created: 0, skipped: 0, errors: 0, details: [] };
    const driversSnap = await db.collection('users').where('role', 'in', ['delivery', 'delivery_agent']).get();
    const driverIds = driversSnap.docs.map(d => d.id);
    let currentDriverIndex = 0;
    const subsSnap = await db.collection('subscriptions').where('status', '==', 'active').get();
    if (subsSnap.empty)
        return result;
    const existingSubIds = new Set();
    if (!force) {
        const todayStart = new Date();
        todayStart.setHours(0, 0, 0, 0);
        const todayEnd = new Date();
        todayEnd.setHours(23, 59, 59, 999);
        const existingSnap = await db.collection('orders')
            .where('created_at', '>=', admin.firestore.Timestamp.fromDate(todayStart))
            .where('created_at', '<=', admin.firestore.Timestamp.fromDate(todayEnd))
            .get();
        existingSnap.forEach((d) => {
            const docData = d.data();
            if (docData.subscription_id)
                existingSubIds.add(docData.subscription_id);
        });
    }
    const batch = db.batch();
    let batchCount = 0;
    for (const subDoc of subsSnap.docs) {
        const sub = subDoc.data();
        const subId = subDoc.id;
        if (existingSubIds.has(subId)) {
            result.skipped++;
            result.details.push({ subId, userName: sub.user_id, status: 'skipped', reason: 'Order already exists today' });
            continue;
        }
        try {
            const [userSnap, vendorSnap] = await Promise.all([
                db.collection('users').doc(sub.user_id).get(),
                db.collection('users').doc(sub.vendor_id).get(),
            ]);
            const user = userSnap.exists ? userSnap.data() : null;
            const vendor = vendorSnap.exists ? vendorSnap.data() : null;
            if (!user || !vendor) {
                result.errors++;
                result.details.push({ subId, userName: sub.user_id, status: 'error', reason: 'User or vendor profile not found' });
                continue;
            }
            const mealTypesToGenerate = sub.meal_type === 'both' ? ['lunch', 'dinner'] : [sub.meal_type];
            const userLat = user.location?.lat ?? 18.5204;
            const userLng = user.location?.lng ?? 73.8567;
            for (const mealType of mealTypesToGenerate) {
                const mealName = mealType === 'dinner' ? 'Dinner' : 'Lunch';
                const otp = String(Math.floor(1000 + Math.random() * 9000));
                const assignedDriverId = driverIds.length > 0 ? driverIds[currentDriverIndex++ % driverIds.length] : null;
                const scheduledSlot = mealType === 'lunch' ? (user.deliveryPreference || '11am') : '8pm';
                const newOrderRef = db.collection('orders').doc();
                const todayStr = new Date().toISOString().split('T')[0];
                batch.set(newOrderRef, {
                    order_id: newOrderRef.id,
                    user_id: sub.user_id,
                    customer_phone: user.phone || user.phoneNumber || '',
                    subscription_id: subId,
                    date: todayStr,
                    meal_type: mealType,
                    delivery_slot: scheduledSlot,
                    vendor_id: sub.vendor_id,
                    vendor_phone: vendor.phone || vendor.phoneNumber || '',
                    batch_id: null,
                    delivery_address: {
                        line1: user.address || `${user.name}'s Location`,
                        lat: userLat,
                        lng: userLng,
                    },
                    status: 'created',
                    otp: otp,
                    rider_trip_id: null,
                    swap_ref: null,
                    skip_ref: null,
                    created_at: admin.firestore.FieldValue.serverTimestamp(),
                    updated_at: admin.firestore.FieldValue.serverTimestamp()
                });
                (0, events_1.publishEvent)('order_confirmed', sub.user_id, 'customer', `order_confirmed_${newOrderRef.id}`, {
                    mealType: mealName,
                    slot: scheduledSlot
                }).catch(err => console.error('Error publishing order_confirmed:', err));
                batchCount++;
            }
            result.created += mealTypesToGenerate.length;
            result.details.push({ subId, userName: user.name || sub.user_id, status: 'created', generatedOrders: mealTypesToGenerate.length });
            if (batchCount >= 490) {
                await batch.commit();
                batchCount = 0;
            }
        }
        catch (err) {
            result.errors++;
            result.details.push({ subId, userName: sub.user_id, status: 'error', reason: err.message || 'Unknown error' });
        }
    }
    if (batchCount > 0) {
        await batch.commit();
    }
    return result;
}
exports.generateTodayDeliveries = (0, https_1.onCall)(async (request) => {
    const { auth, data } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    if (auth.token.role !== 'admin') {
        const userDoc = await admin.firestore().collection('users').doc(auth.uid).get();
        if (!userDoc.exists || userDoc.data()?.role !== 'admin') {
            throw new https_1.HttpsError('permission-denied', 'Must be an admin to generate orders');
        }
    }
    const force = data?.force === true;
    return await processDailyDeliveries(force);
});
exports.autoGenerateDailyDeliveries = (0, scheduler_1.onSchedule)({
    schedule: '0 1 * * *',
    timeZone: 'Asia/Kolkata'
}, async (event) => {
    console.log('[autoGenerateDailyDeliveries] Starting scheduled order generation...');
    const result = await processDailyDeliveries(false);
    console.log(`[autoGenerateDailyDeliveries] Completed. Created: ${result.created}, Skipped: ${result.skipped}, Errors: ${result.errors}`);
});
exports.markBatchReady = (0, https_1.onCall)(async (request) => {
    const { auth, data } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    const vendorId = auth.uid;
    const { batch_id } = data;
    if (!batch_id) {
        throw new https_1.HttpsError('invalid-argument', 'Missing batch_id');
    }
    const db = admin.firestore();
    const batchRef = db.collection('batches').doc(batch_id);
    const result = await db.runTransaction(async (t) => {
        const batchDoc = await t.get(batchRef);
        if (!batchDoc.exists) {
            throw new https_1.HttpsError('not-found', `Batch ${batch_id} not found`);
        }
        const batch = batchDoc.data();
        if (batch.vendor_id !== vendorId) {
            throw new https_1.HttpsError('permission-denied', 'This batch does not belong to you');
        }
        if (batch.status === 'ready' || batch.status === 'completed') {
            return { success: false, message: `Batch is already in status: ${batch.status}` };
        }
        const orderIds = batch.order_ids || [];
        const orderDocs = [];
        for (const orderId of orderIds) {
            const orderRef = db.collection('orders').doc(orderId);
            const orderDoc = await t.get(orderRef);
            orderDocs.push(orderDoc);
        }
        const pickupOTP = Math.floor(1000 + Math.random() * 9000).toString();
        t.update(batchRef, {
            status: 'ready',
            pickup_otp: pickupOTP,
            updated_at: admin.firestore.FieldValue.serverTimestamp()
        });
        let cascadeCount = 0;
        for (const orderDoc of orderDocs) {
            if (!orderDoc.exists)
                continue;
            const order = orderDoc.data();
            const skipStatuses = ['skipped', 'swapped_out', 'failed', 'completed'];
            if (skipStatuses.includes(order.status))
                continue;
            t.update(orderDoc.ref, {
                status: 'vendor_ready',
                updated_at: admin.firestore.FieldValue.serverTimestamp()
            });
            const logRef = db.collection('order_status_logs').doc();
            t.set(logRef, {
                id: logRef.id,
                order_id: orderDoc.id,
                from_status: order.status,
                to_status: 'vendor_ready',
                actor: vendorId,
                timestamp: admin.firestore.FieldValue.serverTimestamp()
            });
            (0, events_1.publishEvent)('meal_prep_started', order.user_id, 'customer', `meal_prep_${orderDoc.id}`, { mealType: order.meal_type || 'meal' }).catch(e => console.error('[markBatchReady] Failed to publish customer event:', e));
            cascadeCount++;
        }
        return { success: true, message: `Batch marked ready. ${cascadeCount} orders updated to vendor_ready.` };
    });
    try {
        const m = await Promise.resolve().then(() => __importStar(require('./matchingTriggers')));
        await m.coreAssignRiderTrips(vendorId);
    }
    catch (e) {
        console.error('[markBatchReady] Auto-assign failed:', e);
    }
    return result;
});
exports.onSubscriptionCreated = (0, firestore_1.onDocumentWritten)('subscriptions/{subId}', async (event) => {
    const before = event.data?.before;
    const after = event.data?.after;
    if (!after?.exists)
        return;
    const afterData = after.data();
    if (!afterData || afterData.status !== 'active')
        return;
    const beforeData = before?.exists ? before.data() : null;
    if (beforeData && beforeData.status === 'active')
        return;
    const db = admin.firestore();
    const sub = afterData;
    const subId = event.params.subId;
    const [userSnap, vendorSnap] = await Promise.all([
        db.collection('users').doc(sub.user_id).get(),
        db.collection('users').doc(sub.vendor_id).get(),
    ]);
    const user = userSnap.exists ? userSnap.data() : null;
    const vendor = vendorSnap.exists ? vendorSnap.data() : null;
    if (!user || !vendor) {
        console.error(`[onSubscriptionCreated] User or vendor not found for sub ${subId}`);
        return;
    }
    const driversSnap = await db.collection('users').where('role', 'in', ['delivery', 'delivery_agent']).get();
    const driverIds = driversSnap.docs.map(d => d.id);
    const mealTypes = sub.meal_type === 'both' ? ['lunch', 'dinner'] : [sub.meal_type];
    const userLat = user.location?.lat ?? 18.5204;
    const userLng = user.location?.lng ?? 73.8567;
    const now = new Date();
    const istOffset = 5.5 * 60 * 60 * 1000;
    const istNow = new Date(now.getTime() + istOffset);
    const istHour = istNow.getUTCHours();
    const existingSnap = await db.collection('delivery_orders')
        .where('subscriptionId', '==', subId)
        .where('status', '==', 'pending')
        .get();
    const cleanBatch = db.batch();
    existingSnap.docs.forEach(d => cleanBatch.delete(d.ref));
    if (!existingSnap.empty)
        await cleanBatch.commit();
    const batch = db.batch();
    let driverIdx = 0;
    let ordersCreated = 0;
    for (let dayOffset = 0; dayOffset <= 5; dayOffset++) {
        for (const mealType of mealTypes) {
            if (dayOffset === 0) {
                if (mealType === 'lunch' && istHour >= 10)
                    continue;
                if (mealType === 'dinner' && istHour >= 19)
                    continue;
            }
            const mealName = mealType === 'dinner' ? 'Dinner' : 'Lunch';
            const scheduledSlot = mealType === 'lunch' ? (user.deliveryPreference || '11am') : '8pm';
            const orderDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() + dayOffset);
            const assignedDriverId = driverIds.length > 0 ? driverIds[driverIdx++ % driverIds.length] : null;
            const otp = String(Math.floor(1000 + Math.random() * 9000));
            const newOrderRef = db.collection('delivery_orders').doc();
            batch.set(newOrderRef, {
                subscriptionId: subId,
                customerId: sub.user_id,
                customerPhone: user.phone || user.phoneNumber || '',
                vendorId: sub.vendor_id,
                vendorPhone: vendor.phone || vendor.phoneNumber || '',
                driverId: assignedDriverId,
                status: 'pending',
                otp,
                otpVerified: false,
                meal: {
                    name: `${vendor.kitchen_name || vendor.name}'s ${mealName}`,
                    type: mealType,
                },
                address: {
                    line1: user.address || `${user.name}'s Location`,
                    landmark: '',
                    lat: userLat,
                    lng: userLng,
                },
                driverLocation: null,
                scheduledSlot,
                timestamps: { preparedAt: null, pickedAt: null, outAt: null, deliveredAt: null },
                createdAt: admin.firestore.Timestamp.fromDate(orderDate),
            });
            ordersCreated++;
        }
    }
    if (ordersCreated > 0)
        await batch.commit();
    console.log(`[onSubscriptionCreated] Generated ${ordersCreated} delivery orders for sub ${subId}`);
});
exports.onSubscriptionCancelled = (0, firestore_1.onDocumentUpdated)('subscriptions/{subId}', async (event) => {
    const before = event.data?.before.data();
    const after = event.data?.after.data();
    if (!before || !after)
        return;
    if (before.status === after.status || after.status !== 'cancelled')
        return;
    const subId = event.params.subId;
    const db = admin.firestore();
    console.log(`[onSubscriptionCancelled] Cancelling future delivery orders for sub ${subId}`);
    const ordersSnap = await db.collection('delivery_orders')
        .where('subscriptionId', '==', subId)
        .where('status', 'in', ['pending', 'preparing'])
        .get();
    if (ordersSnap.empty) {
        console.log(`[onSubscriptionCancelled] No pending orders found for sub ${subId}`);
        return;
    }
    const batch = db.batch();
    ordersSnap.docs.forEach(doc => {
        batch.update(doc.ref, {
            status: 'cancelled',
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
    });
    await batch.commit();
    console.log(`[onSubscriptionCancelled] Cancelled ${ordersSnap.size} delivery orders for sub ${subId}`);
});
exports.generateTestDelivery = (0, https_1.onCall)(async (request) => {
    const { auth } = request;
    if (!auth)
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    if (auth.token.role !== 'admin') {
        const callerDoc = await admin.firestore().collection('users').doc(auth.uid).get();
        if (!callerDoc.exists || callerDoc.data()?.role !== 'admin') {
            throw new https_1.HttpsError('permission-denied', 'Must be an admin to run test delivery flow');
        }
    }
    const db = admin.firestore();
    const findUser = async (phone, role) => {
        const snap = await db.collection('users').where('phone', '==', phone).limit(1).get();
        if (snap.empty) {
            throw new https_1.HttpsError('not-found', `Could not find ${role} with phone ${phone}`);
        }
        return snap.docs[0];
    };
    const [userDoc, vendorDoc, riderDoc] = await Promise.all([
        findUser('+919900990011', 'customer'),
        findUser('+919900990022', 'vendor'),
        findUser('+919900990044', 'rider')
    ]);
    const customerId = userDoc.id;
    const vendorId = vendorDoc.id;
    const riderId = riderDoc.id;
    const todayStr = new Date().toLocaleString('en-CA', { timeZone: 'Asia/Kolkata' }).split(',')[0];
    const existingOrders = await db.collection('orders')
        .where('user_id', '==', customerId)
        .where('date', '==', todayStr)
        .get();
    for (const doc of existingOrders.docs) {
        await doc.ref.delete();
    }
    const existingBatches = await db.collection('batches')
        .where('vendor_id', '==', vendorId)
        .get();
    for (const doc of existingBatches.docs) {
        await doc.ref.delete();
    }
    const existingTrips = await db.collection('rider_trips')
        .where('riderId', '==', riderId)
        .get();
    for (const doc of existingTrips.docs) {
        await doc.ref.delete();
    }
    const batchId = `TEST_BATCH_${vendorId}_${todayStr}`;
    const tripId = `TEST_TRIP_${riderId}_${todayStr}`;
    const vendorLocation = vendorDoc.data()?.location || { lat: 0, lng: 0 };
    const customerLocation = userDoc.data()?.location || { lat: 0, lng: 0 };
    const customerAddress = userDoc.data()?.address || { line1: 'Test Address' };
    const orderRef = db.collection('orders').doc();
    const orderData = {
        id: orderRef.id,
        user_id: customerId,
        vendor_id: vendorId,
        agent_id: riderId,
        rider_trip_id: tripId,
        driverId: riderId,
        customerId: customerId,
        vendorId: vendorId,
        address: customerAddress,
        date: todayStr,
        status: 'vendor_ready',
        delivery_slot: '11am',
        meal_type: 'lunch',
        otp: Math.floor(1000 + Math.random() * 9000).toString(),
        created_at: admin.firestore.FieldValue.serverTimestamp(),
        updated_at: admin.firestore.FieldValue.serverTimestamp()
    };
    await orderRef.set(orderData);
    const batchRef = db.collection('batches').doc(batchId);
    const pickupOTP = Math.floor(1000 + Math.random() * 9000).toString();
    const batchData = {
        id: batchId,
        vendor_id: vendorId,
        date: todayStr,
        slot: '11am',
        order_ids: [orderRef.id],
        status: 'ready',
        pickup_otp: pickupOTP,
        created_at: admin.firestore.FieldValue.serverTimestamp(),
        updated_at: admin.firestore.FieldValue.serverTimestamp()
    };
    await batchRef.set(batchData);
    const tripRef = db.collection('rider_trips').doc(tripId);
    const tripData = {
        id: tripId,
        riderId: riderId,
        batch_ids: [batchId],
        assignedOrderIds: [orderRef.id],
        vendorIds: [vendorId],
        status: 'pickup_pending',
        pickupStops: [
            {
                vendorId: vendorId,
                vendorPhone: vendorDoc.data()?.phone,
                location: vendorLocation,
                sequence: 1,
                distanceKm: 0,
                status: 'pending',
                pickupOTP: pickupOTP
            }
        ],
        dropoffStops: [
            {
                orderId: orderRef.id,
                customerId: customerId,
                address: 'Test Customer Address',
                status: 'pending',
                lat: 21.1500,
                lng: 79.0900
            }
        ],
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
    };
    await tripRef.set(tripData);
    await batchRef.update({
        status: 'ready',
        agent_id: riderId
    });
    return {
        success: true,
        orderId: orderRef.id,
        batchId: batchId,
        tripId: tripId,
        message: 'Test delivery flow successfully generated!'
    };
});
//# sourceMappingURL=deliveryTriggers.js.map