"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.onSubscriptionCancelled = exports.onSubscriptionCreated = exports.markBatchReady = exports.autoGenerateDailyDeliveries = exports.generateTodayDeliveries = exports.updateDeliveryStatus = exports.onDeliveryStatusChange = void 0;
const firestore_1 = require("firebase-functions/v2/firestore");
const https_1 = require("firebase-functions/v2/https");
const scheduler_1 = require("firebase-functions/v2/scheduler");
const admin = __importStar(require("firebase-admin"));
const events_1 = require("./utils/events");
exports.onDeliveryStatusChange = (0, firestore_1.onDocumentUpdated)('delivery_orders/{orderId}', async (event) => {
    const change = event.data;
    if (!change) {
        console.log('[onDeliveryStatusChange] No data change payload.');
        return;
    }
    const beforeData = change.before.data();
    const afterData = change.after.data();
    if (!beforeData || !afterData) {
        console.log('[onDeliveryStatusChange] Document state empty.');
        return;
    }
    const beforeStatus = beforeData.status;
    const afterStatus = afterData.status;
    if (beforeStatus === afterStatus) {
        console.log(`[onDeliveryStatusChange] Status unchanged (${afterStatus}). Returning.`);
        return;
    }
    const db = admin.firestore();
    const messaging = admin.messaging();
    const orderId = event.params.orderId;
    console.log(`[onDeliveryStatusChange] Transit status updated: ${beforeStatus} -> ${afterStatus} for order: ${orderId}`);
    try {
        const customerId = afterData.customerId;
        const vendorId = afterData.vendorId;
        if (afterStatus === 'picked_up') {
            const vendorSnap = await db.collection('users').doc(vendorId).get();
            const vendorName = vendorSnap.exists
                ? (vendorSnap.data()?.name || 'Dabzo Partner Kitchen')
                : 'Dabzo Partner Kitchen';
            let eta = '1:30 PM';
            if (afterData.scheduledSlot === '8am')
                eta = '8:30 AM';
            else if (afterData.scheduledSlot === '11am')
                eta = '11:30 AM';
            else if (afterData.scheduledSlot === '8pm' || afterData.meal?.type === 'dinner')
                eta = '8:30 PM';
            await sendFCMToUser(customerId, {
                title: 'Your tiffin is on the way!',
                body: `Picked up from ${vendorName}. Estimated delivery: ${eta}`,
            });
        }
        else if (afterStatus === 'out_for_delivery') {
            const otp = afterData.otp || '0000';
            await sendFCMToUser(customerId, {
                title: 'Driver is nearby',
                body: `Your OTP is ${otp}. Show it to confirm delivery.`,
            });
        }
        else if (afterStatus === 'delivered') {
            const customerSnap = await db.collection('users').doc(customerId).get();
            const customerName = customerSnap.exists
                ? (customerSnap.data()?.name || 'Subscriber')
                : 'Subscriber';
            await Promise.all([
                sendFCMToUser(customerId, {
                    title: 'Delivered!',
                    body: 'Enjoy your meal! Rate your experience.',
                }),
                sendFCMToUser(vendorId, {
                    title: 'Delivery confirmed',
                    body: `${customerName}'s order delivered successfully.`,
                }),
            ]);
        }
        else if (afterStatus === 'failed') {
            const adminSnap = await db.collection('users').where('role', '==', 'admin').get();
            const adminTokens = [];
            adminSnap.forEach((docSnap) => {
                const u = docSnap.data();
                if (u.fcmToken) {
                    adminTokens.push(u.fcmToken);
                }
                if (u.push_tokens && Array.isArray(u.push_tokens)) {
                    adminTokens.push(...u.push_tokens);
                }
            });
            if (adminTokens.length > 0) {
                const uniqueTokens = Array.from(new Set(adminTokens));
                await sendMulticastFCM(uniqueTokens, {
                    title: 'Delivery failed',
                    body: `Order ${orderId} failed. Review in admin panel.`,
                });
            }
        }
    }
    catch (err) {
        console.error(`[onDeliveryStatusChange] Failed processing push trigger for ${orderId}:`, err);
    }
    async function sendFCMToUser(uid, payload) {
        const userSnap = await db.collection('users').doc(uid).get();
        if (!userSnap.exists) {
            console.log(`[onDeliveryStatusChange] User profile not found: ${uid}`);
            return;
        }
        const userData = userSnap.data();
        const tokens = [];
        if (userData.fcmToken) {
            tokens.push(userData.fcmToken);
        }
        if (userData.push_tokens && Array.isArray(userData.push_tokens)) {
            tokens.push(...userData.push_tokens);
        }
        if (tokens.length === 0) {
            console.log(`[onDeliveryStatusChange] No device FCM token registered for ${uid}`);
            return;
        }
        const uniqueTokens = Array.from(new Set(tokens));
        await sendMulticastFCM(uniqueTokens, payload);
    }
    async function sendMulticastFCM(tokens, payload) {
        console.log(`[onDeliveryStatusChange] Dispatching multicast to ${tokens.length} channels...`);
        try {
            await messaging.sendEachForMulticast({
                tokens,
                notification: {
                    title: payload.title,
                    body: payload.body,
                },
                android: {
                    notification: {
                        channelId: 'default',
                        priority: 'high',
                    },
                },
                apns: {
                    payload: {
                        aps: {
                            sound: 'default',
                        },
                    },
                },
            });
            console.log('[onDeliveryStatusChange] Multicast push dispatched successfully.');
        }
        catch (e) {
            console.error('[onDeliveryStatusChange] Messaging payload transmission failure:', e);
        }
    }
});
exports.updateDeliveryStatus = (0, https_1.onCall)(async (request) => {
    const { data, auth } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    if (auth.token.role !== 'delivery_agent' && auth.token.role !== 'delivery') {
        throw new https_1.HttpsError('permission-denied', 'Must be a delivery agent to update status');
    }
    const { orderId, status, reason } = data;
    if (!orderId || !status) {
        throw new https_1.HttpsError('invalid-argument', 'Missing orderId or status');
    }
    const db = admin.firestore();
    const deliveryRef = db.collection('deliveries').doc(orderId);
    const transitionResult = await db.runTransaction(async (transaction) => {
        const docSnap = await transaction.get(deliveryRef);
        if (!docSnap.exists) {
            throw new https_1.HttpsError('not-found', 'Delivery order not found');
        }
        const deliveryData = docSnap.data();
        if (deliveryData.agentId !== auth.uid) {
            throw new https_1.HttpsError('permission-denied', 'You are not assigned to this delivery');
        }
        const currentStatus = deliveryData.status;
        if (status === 'picked_up' && currentStatus !== 'pending') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to picked_up from pending');
        }
        if (status === 'delivered' && currentStatus !== 'picked_up') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to delivered from picked_up');
        }
        if (status === 'failed_attempt' && currentStatus !== 'picked_up') {
            throw new https_1.HttpsError('failed-precondition', 'Can only transition to failed_attempt from picked_up');
        }
        if (status === 'failed_attempt' && (!reason || reason.trim() === '')) {
            throw new https_1.HttpsError('invalid-argument', 'Must provide a non-empty reason when setting status to failed_attempt');
        }
        const updatePayload = {
            status,
            statusHistory: admin.firestore.FieldValue.arrayUnion({
                status,
                timestamp: admin.firestore.FieldValue.serverTimestamp(),
                agentId: auth.uid
            })
        };
        if (status === 'delivered') {
            updatePayload.delivered_at = admin.firestore.FieldValue.serverTimestamp();
        }
        else if (status === 'failed_attempt') {
            updatePayload.failedReason = reason;
        }
        transaction.update(deliveryRef, updatePayload);
        return {
            customerId: deliveryData.customerId,
            vendorId: deliveryData.vendorId,
            oldStatus: currentStatus,
            newStatus: status,
            reason: reason
        };
    });
    try {
        const { customerId, newStatus, reason } = transitionResult;
        if (newStatus === 'picked_up') {
            await (0, events_1.publishEvent)('meal_picked_up', customerId, 'customer', `meal_picked_up_${orderId}`, { orderId });
        }
        else if (newStatus === 'delivered') {
            await (0, events_1.publishEvent)('meal_delivered', customerId, 'customer', `meal_delivered_${orderId}`, { orderId });
        }
        else if (newStatus === 'failed_attempt') {
            await (0, events_1.publishEvent)('delivery_failed', customerId, 'customer', `delivery_failed_${orderId}`, { orderId, reason: reason ?? '' });
            const adminSnap = await db.collection('users').where('role', '==', 'admin').get();
            await Promise.all(adminSnap.docs.map((adminDoc) => (0, events_1.publishEvent)('delivery_failed', adminDoc.id, 'admin', `delivery_failed_admin_${orderId}_${adminDoc.id}`, { orderId, reason: reason ?? '' })));
        }
    }
    catch (error) {
        console.error(`[updateDeliveryStatus] Push notification error for order ${orderId}:`, error);
    }
    return {
        success: true,
        newStatus: transitionResult.newStatus,
        message: `Successfully updated order status to ${transitionResult.newStatus}`
    };
});
async function processDailyDeliveries(force = false) {
    const db = admin.firestore();
    const result = { created: 0, skipped: 0, errors: 0, details: [] };
    const driversSnap = await db.collection('users').where('role', 'in', ['delivery', 'delivery_agent']).get();
    const driverIds = driversSnap.docs.map(d => d.id);
    let currentDriverIndex = 0;
    const subsSnap = await db.collection('subscriptions').where('status', '==', 'active').get();
    if (subsSnap.empty)
        return result;
    const existingSubIds = new Set();
    if (!force) {
        const todayStart = new Date();
        todayStart.setHours(0, 0, 0, 0);
        const todayEnd = new Date();
        todayEnd.setHours(23, 59, 59, 999);
        const existingSnap = await db.collection('delivery_orders')
            .where('createdAt', '>=', admin.firestore.Timestamp.fromDate(todayStart))
            .where('createdAt', '<=', admin.firestore.Timestamp.fromDate(todayEnd))
            .get();
        existingSnap.forEach((d) => {
            const docData = d.data();
            if (docData.subscriptionId)
                existingSubIds.add(docData.subscriptionId);
        });
    }
    const batch = db.batch();
    let batchCount = 0;
    for (const subDoc of subsSnap.docs) {
        const sub = subDoc.data();
        const subId = subDoc.id;
        if (existingSubIds.has(subId)) {
            result.skipped++;
            result.details.push({ subId, userName: sub.user_id, status: 'skipped', reason: 'Order already exists today' });
            continue;
        }
        try {
            const [userSnap, vendorSnap] = await Promise.all([
                db.collection('users').doc(sub.user_id).get(),
                db.collection('users').doc(sub.vendor_id).get(),
            ]);
            const user = userSnap.exists ? userSnap.data() : null;
            const vendor = vendorSnap.exists ? vendorSnap.data() : null;
            if (!user || !vendor) {
                result.errors++;
                result.details.push({ subId, userName: sub.user_id, status: 'error', reason: 'User or vendor profile not found' });
                continue;
            }
            const mealTypesToGenerate = sub.meal_type === 'both' ? ['lunch', 'dinner'] : [sub.meal_type];
            const userLat = user.location?.lat ?? 18.5204;
            const userLng = user.location?.lng ?? 73.8567;
            for (const mealType of mealTypesToGenerate) {
                const mealName = mealType === 'dinner' ? 'Dinner' : 'Lunch';
                const otp = String(Math.floor(1000 + Math.random() * 9000));
                const assignedDriverId = driverIds.length > 0 ? driverIds[currentDriverIndex++ % driverIds.length] : null;
                const scheduledSlot = mealType === 'lunch' ? (user.deliveryPreference || '11am') : '8pm';
                const newOrderRef = db.collection('delivery_orders').doc();
                batch.set(newOrderRef, {
                    subscriptionId: subId,
                    customerId: sub.user_id,
                    customerPhone: user.phone || user.phoneNumber || '',
                    vendorId: sub.vendor_id,
                    vendorPhone: vendor.phone || vendor.phoneNumber || '',
                    driverId: assignedDriverId,
                    status: 'preparing',
                    otp,
                    otpVerified: false,
                    meal: {
                        name: `${vendor.kitchen_name || vendor.name}'s ${mealName}`,
                        type: mealType,
                    },
                    address: {
                        line1: user.address || `${user.name}'s Location`,
                        landmark: '',
                        lat: userLat,
                        lng: userLng,
                    },
                    driverLocation: null,
                    scheduledSlot: scheduledSlot,
                    timestamps: {
                        preparedAt: null,
                        pickedAt: null,
                        outAt: null,
                        deliveredAt: null,
                    },
                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                });
                (0, events_1.publishEvent)('order_confirmed', sub.user_id, 'customer', `order_confirmed_${newOrderRef.id}`, {
                    mealType: mealName,
                    slot: scheduledSlot
                }).catch(err => console.error('Error publishing order_confirmed:', err));
                batchCount++;
            }
            result.created += mealTypesToGenerate.length;
            result.details.push({ subId, userName: user.name || sub.user_id, status: 'created', generatedOrders: mealTypesToGenerate.length });
            if (batchCount >= 490) {
                await batch.commit();
                batchCount = 0;
            }
        }
        catch (err) {
            result.errors++;
            result.details.push({ subId, userName: sub.user_id, status: 'error', reason: err.message || 'Unknown error' });
        }
    }
    if (batchCount > 0) {
        await batch.commit();
    }
    return result;
}
exports.generateTodayDeliveries = (0, https_1.onCall)(async (request) => {
    const { auth, data } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    if (auth.token.role !== 'admin') {
        const userDoc = await admin.firestore().collection('users').doc(auth.uid).get();
        if (!userDoc.exists || userDoc.data()?.role !== 'admin') {
            throw new https_1.HttpsError('permission-denied', 'Must be an admin to generate orders');
        }
    }
    const force = data?.force === true;
    return await processDailyDeliveries(force);
});
exports.autoGenerateDailyDeliveries = (0, scheduler_1.onSchedule)({
    schedule: '0 1 * * *',
    timeZone: 'Asia/Kolkata'
}, async (event) => {
    console.log('[autoGenerateDailyDeliveries] Starting scheduled order generation...');
    const result = await processDailyDeliveries(false);
    console.log(`[autoGenerateDailyDeliveries] Completed. Created: ${result.created}, Skipped: ${result.skipped}, Errors: ${result.errors}`);
});
exports.markBatchReady = (0, https_1.onCall)(async (request) => {
    const { auth, data } = request;
    if (!auth) {
        throw new https_1.HttpsError('unauthenticated', 'Must be authenticated');
    }
    const vendorId = auth.uid;
    const { dateStr, slot } = data;
    if (!dateStr || !slot) {
        throw new https_1.HttpsError('invalid-argument', 'Missing dateStr or slot');
    }
    const batchId = `${vendorId}_${dateStr}_${slot}`;
    const batchRef = admin.firestore().collection('vendor_batches').doc(batchId);
    return await admin.firestore().runTransaction(async (t) => {
        const batchDoc = await t.get(batchRef);
        if (batchDoc.exists) {
            return { success: false, message: 'Batch already marked ready' };
        }
        const ordersQuery = admin.firestore().collection('delivery_orders')
            .where('vendorId', '==', vendorId)
            .where('scheduledSlot', '==', slot)
            .where('status', 'in', ['pending', 'preparing']);
        const ordersSnap = await t.get(ordersQuery);
        let updatedCount = 0;
        ordersSnap.docs.forEach(doc => {
            const orderData = doc.data();
            const oDateStr = orderData.createdAt?.toDate ? orderData.createdAt.toDate().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }) : new Date().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
            if (oDateStr === dateStr) {
                t.update(doc.ref, { status: 'ready', updatedAt: admin.firestore.FieldValue.serverTimestamp() });
                updatedCount++;
                (0, events_1.publishEvent)('meal_prep_started', orderData.customerId, 'customer', `meal_prep_started_${doc.id}`, { mealType: orderData.meal?.name || 'meal' }).catch(e => console.error(e));
            }
        });
        t.set(batchRef, {
            vendorId,
            date: dateStr,
            slot,
            status: 'ready',
            updatedCount,
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });
        return { success: true, message: `Batch marked ready. ${updatedCount} orders updated.` };
    });
});
exports.onSubscriptionCreated = (0, firestore_1.onDocumentWritten)('subscriptions/{subId}', async (event) => {
    const before = event.data?.before;
    const after = event.data?.after;
    if (!after?.exists)
        return;
    const afterData = after.data();
    if (!afterData || afterData.status !== 'active')
        return;
    const beforeData = before?.exists ? before.data() : null;
    if (beforeData && beforeData.status === 'active')
        return;
    const db = admin.firestore();
    const sub = afterData;
    const subId = event.params.subId;
    const [userSnap, vendorSnap] = await Promise.all([
        db.collection('users').doc(sub.user_id).get(),
        db.collection('users').doc(sub.vendor_id).get(),
    ]);
    const user = userSnap.exists ? userSnap.data() : null;
    const vendor = vendorSnap.exists ? vendorSnap.data() : null;
    if (!user || !vendor) {
        console.error(`[onSubscriptionCreated] User or vendor not found for sub ${subId}`);
        return;
    }
    const driversSnap = await db.collection('users').where('role', 'in', ['delivery', 'delivery_agent']).get();
    const driverIds = driversSnap.docs.map(d => d.id);
    const mealTypes = sub.meal_type === 'both' ? ['lunch', 'dinner'] : [sub.meal_type];
    const userLat = user.location?.lat ?? 18.5204;
    const userLng = user.location?.lng ?? 73.8567;
    const now = new Date();
    const istOffset = 5.5 * 60 * 60 * 1000;
    const istNow = new Date(now.getTime() + istOffset);
    const istHour = istNow.getUTCHours();
    const existingSnap = await db.collection('delivery_orders')
        .where('subscriptionId', '==', subId)
        .where('status', '==', 'pending')
        .get();
    const cleanBatch = db.batch();
    existingSnap.docs.forEach(d => cleanBatch.delete(d.ref));
    if (!existingSnap.empty)
        await cleanBatch.commit();
    const batch = db.batch();
    let driverIdx = 0;
    let ordersCreated = 0;
    for (let dayOffset = 0; dayOffset <= 5; dayOffset++) {
        for (const mealType of mealTypes) {
            if (dayOffset === 0) {
                if (mealType === 'lunch' && istHour >= 10)
                    continue;
                if (mealType === 'dinner' && istHour >= 19)
                    continue;
            }
            const mealName = mealType === 'dinner' ? 'Dinner' : 'Lunch';
            const scheduledSlot = mealType === 'lunch' ? (user.deliveryPreference || '11am') : '8pm';
            const orderDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() + dayOffset);
            const assignedDriverId = driverIds.length > 0 ? driverIds[driverIdx++ % driverIds.length] : null;
            const otp = String(Math.floor(1000 + Math.random() * 9000));
            const newOrderRef = db.collection('delivery_orders').doc();
            batch.set(newOrderRef, {
                subscriptionId: subId,
                customerId: sub.user_id,
                customerPhone: user.phone || user.phoneNumber || '',
                vendorId: sub.vendor_id,
                vendorPhone: vendor.phone || vendor.phoneNumber || '',
                driverId: assignedDriverId,
                status: 'pending',
                otp,
                otpVerified: false,
                meal: {
                    name: `${vendor.kitchen_name || vendor.name}'s ${mealName}`,
                    type: mealType,
                },
                address: {
                    line1: user.address || `${user.name}'s Location`,
                    landmark: '',
                    lat: userLat,
                    lng: userLng,
                },
                driverLocation: null,
                scheduledSlot,
                timestamps: { preparedAt: null, pickedAt: null, outAt: null, deliveredAt: null },
                createdAt: admin.firestore.Timestamp.fromDate(orderDate),
            });
            ordersCreated++;
        }
    }
    if (ordersCreated > 0)
        await batch.commit();
    console.log(`[onSubscriptionCreated] Generated ${ordersCreated} delivery orders for sub ${subId}`);
});
exports.onSubscriptionCancelled = (0, firestore_1.onDocumentUpdated)('subscriptions/{subId}', async (event) => {
    const before = event.data?.before.data();
    const after = event.data?.after.data();
    if (!before || !after)
        return;
    if (before.status === after.status || after.status !== 'cancelled')
        return;
    const subId = event.params.subId;
    const db = admin.firestore();
    console.log(`[onSubscriptionCancelled] Cancelling future delivery orders for sub ${subId}`);
    const ordersSnap = await db.collection('delivery_orders')
        .where('subscriptionId', '==', subId)
        .where('status', 'in', ['pending', 'preparing'])
        .get();
    if (ordersSnap.empty) {
        console.log(`[onSubscriptionCancelled] No pending orders found for sub ${subId}`);
        return;
    }
    const batch = db.batch();
    ordersSnap.docs.forEach(doc => {
        batch.update(doc.ref, {
            status: 'cancelled',
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
    });
    await batch.commit();
    console.log(`[onSubscriptionCancelled] Cancelled ${ordersSnap.size} delivery orders for sub ${subId}`);
});
//# sourceMappingURL=deliveryTriggers.js.map